/* Replace with your SQL commands */
CREATE TABLE public.user_info (
    id integer primary key generated by default as identity,
    user_id int NOT NULL,
    location varchar(10485760) NULL,
    photo_url varchar(10485760) NULL,
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),
    resource_id varchar(10485760) NOT NULL,
    CONSTRAINT user_info_resource_id_uq UNIQUE (resource_id),
    CONSTRAINT user_info_user_id_uq UNIQUE (user_id),
    CONSTRAINT user_info_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.puppies (
    id integer primary key generated by default as identity,
    user_id int NOT NULL,
    breed varchar(10485760) NOT NULL,
    name varchar(10485760) NOT NULL,
    size varchar(10485760) NOT NULL,
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),
    resource_id varchar(10485760) NOT NULL,
    CONSTRAINT puppies_resource_id_uq UNIQUE (resource_id),
    CONSTRAINT puppies_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);

CREATE TABLE public.photos (
    id integer primary key generated by default as identity,
    puppy_id int NOT NULL,
    url varchar(10485760) NOT NULL,
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),
    resource_id varchar(10485760) NOT NULL,
    CONSTRAINT photos_resource_id_uq UNIQUE (resource_id),
    CONSTRAINT photos_puppy_id_fk FOREIGN KEY (puppy_id) REFERENCES public.puppies(id)
);

CREATE TABLE public.messages (
    id integer primary key generated by default as identity,
    from_user_id int NOT NULL,
    to_user_id int NOT NULL,
    message varchar(10485760) NOT NULL,
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),
    resource_id varchar(10485760) NOT NULL,
    CONSTRAINT messages_resource_id_uq UNIQUE (resource_id),
    CONSTRAINT messages_from_user_id_fk FOREIGN KEY (from_user_id) REFERENCES public.users(id),
    CONSTRAINT messages_to_user_id_fk FOREIGN KEY (to_user_id) REFERENCES public.users(id)
);